### ISSUE TITLE
samples_num_alt_1 not exists in the elastic search index

### ISSUE THREAD

**Issue by SimonLi5601** [macarthur-lab/hail-elasticsearch-pipelines#138]
I used v0.1 version of load_dataset_to_es to load the VCF into Elastic Search. seqr expects a filed "samples_num_alt_1" which doesn't exist in the index schema while I tried to add a dataset into seqr via web interface. But I couldn't find this specific filed in the _mapping/variant. I do see sample_id_num_alt, e.g. S00001_CIDR_num_alt. I have the most updated codes on hail-elasticsearch-pipelines. Could you point me out what I might miss? Thanks!

**Comment by hanars** [comment]
We have upgraded seqr to use the latest version of the pipeline output, which requires you to use the flags `--use-nested-objects-for-vep --use-nested-objects-for-genotypes` when initially running the pipeline

**Comment by SimonLi5601** [comment]
Thanks, @hanars . I must hear those two parameters before, but couldn't figure out where they were. Now I re-run the scripts and see I can make it work to the end. Just curious if this meta data is always expected? and if so,  why it is optional? Sorry that I am asking this kind of question without going through much details into the codes.

**Comment by hanars** [comment]
It is always expected, and its optional because these scripts are old and badly maintained, and we are in the process of completely rewriting them

**Comment by SimonLi5601** [comment]
Yes, it is working now. @hanars, thanks for your time and heads up as well. I will close this ticket now.
