### ISSUE TITLE
Launch Luigi pipeline on Spark

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/hail-elasticsearch-pipelines#181]
Hi,

I need to submit Luigi pipeline to a Spark cluster. I do not see anywhere 'PySparkTask' to be defined/inherited, so does it mean that there is no way to start Luigi on Spark or I just need to write a simple wrapper that would initiate the command:

LUIGI_CONFIG_PATH=configs/seqr-loading-local.cfg python seqr_loading.py SeqrMTToESTask --local-scheduler

specified in the `README.md`? How would you recommend starting it on Spark local cluster (not Google Cloud)?

**Comment by bw2** [comment]
If you run 
```
python3 -u gcloud_dataproc/submit.py --cpu-limit 4 --num-executors 4 --hail-version 0.2  --run-locally luigi_pipeline/seqr_loading.py SeqrVCFToMTTask --local-scheduler --genome-version 38 --sample-type=WGS --genome-version 38 --source-path ./test.vcf.bgz --dest-path test.mt |& grep -v 'has no field'

python3 -u gcloud_dataproc/submit.py --cpu-limit 2 --num-executors 2 --hail-version 0.2  --run-locally luigi_pipeline/seqr_loading.py SeqrMTToESTask --local-scheduler --es-host localhost --es-port 9200 --es-index test
```

It puts together a `spark-submit` command and prints it out before running it. 
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/gcloud_dataproc/submit.py#L49-L66

Is there a way to modify this command to get it to run on your cluster?

**Comment by NLSVTN** [comment]
I tried to use it but it is very hard to debug due to tiny stack trace. I was able to load VCF, it seems, since it writes:

```===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 VcfFile(filename=/sample.vcf)
* 1 failed:
    - 1 SeqrVCFToMTTask(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====```

But then it just fails and I do not know why:

```ERROR: [pid 15160] Worker Worker(salt=945171997, workers=1, host=ai-grisnodedev1, username=seqr, pid=15160) failed    SeqrVCFToMTTask(source_paths=/sample.vcf, dest_path=/seqr-loading-test/sample.mt, genome_version=37, vep_runner=VEP, reference_ht_path=/seqr-reference-data/GRCh37/all_reference_data/combined_reference_data_grch37.ht, clinvar_ht_path=/seqr-reference-data/GRCh37/clinvar/clinvar_37.ht, hgmd_ht_path=/seqr-reference-data/GRCh37/hgmd/hgmd_2019.3_hg19_noDB.ht, sample_type=WES, validate=False, dataset_type=VARIANTS, remap_path=, subset_path=)
Traceback (most recent call last):
  File "/opt/seqr/.conda/envs/py37/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: VcfFile__sample_vcf_a7779ee0cf```

Is there a way to see which is this 'unfulfilled dependency'?

**Comment by NLSVTN** [comment]
In the file **luigi_pipeline/lib/hail_tasks.py** if I check whether the file exists or not in the **__init()__** method:

```
is_present = os.path.isfile(self.source_paths)
logger.warning('********* is_present: %s ***********************' % is_present)
```

Then, supplying the path as **/sample.vcf** when the file is on **hadoop** prints that the file is absent. Ok, if I copy the 'sample.vcf ' file to the current directory and run again, **is_present** is **True**, and the program apparently goes further to start **Hail**, and there it fails because it tries accessing **hadoop** instead of local directory and source_paths is pointing to **local directory** but not **hadoop**. 

Obviously I need everything to be loaded from **hadoop**, so I need a way for **luigi** to accept files from there and not copy all of the files to **local directory**, trying to modify code then to make **hail** accept files from **local directory**. Is it possible to do?

**Comment by NLSVTN** [comment]
Apparently not, at least from what I see in the code. So, I added my own code for HDFSTarget and it passed through the previous errors, and the file was read in, but I got another error in **luigi_pipeline/seqr_loading.py**:

`mt = HailMatrixTableTask.run_vep(mt, self.genome_version, self.vep_runner)`

> java.io.IOException: No FileSystem for scheme: gs

**Comment by NLSVTN** [comment]
Ok, now I see, paths in **hail_scripts/v02/utils/hail_utils.py** to **vep** reference files just need to be adjusted and it should be good to go.

**Comment by NLSVTN** [comment]
I ran the first task **SeqrVCFToMTTask**  successfully but now I am having trouble with the second. I am running it like you specified:

python -u gcloud_dataproc/submit.py --cpu-limit 4 --num-executors 1 --hail-version 0.2 --run-locally luigi_pipeline/seqr_loading.py SeqrMTToESTask --local-scheduler --es-host cp-nodedev1 --es-port 7890 --es-index sample_luigi

And it is giving an error - **requires the 'dest_file' parameter to be set**. By correcting errors, adding **--dest-file** just for **luigi** as **_SUCCESS_TO_ES**, **--source-path** to the **.mt** file of the previous task, then it turns out that I need somehow to specify the initial task too with all of the parameters since I am getting the error:

> luigi.parameter.MissingParameterException: SeqrVCFToMTTask[args=(), kwargs={}]: requires the 'source_paths' parameter to be set

Do you know how I should construct the command in terminal to run **SeqrMTToESTask**? The current command that I have is:

python -u gcloud_dataproc/submit.py --cpu-limit 4 --num-executors 1 --hail-version 0.2 --run-locally luigi_pipeline/seqr_loading.py SeqrMTToESTask --local-scheduler  --dest-file hdfs://.../seqr-loading-test/_SUCCESS_TO_ES --source-path hdfs://.../seqr-loading-test/sample.mt --spark-home $SPARK_HOME --es-host cp-nodedev1 --es-port 7890 --es-index sample_luigi

**Comment by NLSVTN** [comment]
Ok, just figured it out. The right way to go was to specify all of the parameters for all of the tasks in the luigi config file and just feed it into the command. See also:

https://stackoverflow.com/questions/59079716/run-luigi-task-that-depends-on-another-task/59079999#59079999
