### ISSUE TITLE
Update ES index in luigi pipeline instead of recreating it

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/hail-elasticsearch-pipelines#186]
Hi,

In **0.1** pipeline there was a script called **update_reference_data_in_existing_index.py** which allowed us to update already existing index with additional annotations. How would you recommend doing it in **0.2** version? I do not see any scripts there for the purpose, so does it mean that we just need to write our own ones based off **0.1** pipeline? 

Regards.

**Comment by bw2** [comment]
@NLSVTN this hasn't yet been ported to v02 yet. 
I won't be able to work on this for the next few weeks unfortunately.
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/hail_scripts/v01/update_reference_data_in_existing_index.py#L98
@hanars @knguyen142  tagging you in case you can get to it first.

**Comment by NLSVTN** [comment]
Ok, got it

**Comment by NLSVTN** [comment]
I will be done with the update mechanism this Thursday. Going to issue pull request.

**Comment by NLSVTN** [comment]
Hi, how can I contribute the code if you need it? I have it ready.
