### ISSUE TITLE
luigi.parameter._FrozenOrderedDict param issue

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/hail-elasticsearch-pipelines#188]
Hi, 

While I was running your pipeline recently I faced an error on line `54` of the file:

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/luigi_pipeline/lib/hail_tasks.py

`luigi.parameter._FrozenOrderedDict` was giving an error:

>AttributeError: module 'luigi.parameter' has no attribute '_FrozenOrderedDict'

I checked `luigi.parameter` `master` branch and I do not see there `_FrozenOrderedDict`. If we substitute it to `FrozenOrderedDict` without `_`, it works, but I am not sure whether it is safe to do that. Do you know why this is happening? Not sure, but it can be a bug.

**Comment by knguyen142** [comment]
@bw2 Looks like this was your change?

**Comment by NLSVTN** [comment]
Might need to be reopened. There seems to be different environments where either of **_FrozenOrderedDict** or **FrozenOrderedDict** works, so the issue may need to be reopened and checked. I just ran **luigi** in a local and **_FrozenOrderedDict** works, but not **FrozenOrderedDict**. I think before I was running it with spark and on **AWS** cluster and somehow **FrozenOrderedDict** worked, but not **_FrozenOrderedDict**.

I do not know the reason, and going to run it on AWS cluster soon to verify the issue.

**Comment by NLSVTN** [comment]
Yes, thats right: on AWS `FrozenOrderedDict` is working, but locally `_FrozenOrderedDict` is right. I do not know why.
