### ISSUE TITLE
How dataset_type is used in luigi pipeline?

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/hail-elasticsearch-pipelines#210]
There is a parameter in luigi_pipeline - dataset_type. Is it used anywhere in it? I can't see the code somehow for how it is utilized anywhere in the pipeline:

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/42ddf5e5105f600786c3a4c4fd105676ec6d8ab3/luigi_pipeline/seqr_loading.py#L35

You seem to have a separate file - https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/sv_pipeline/load_data.py - for SVs, so does it mean that we should run it separately for SVs instead of the luigi one?

**Comment by hanars** [comment]
It is used for a bunch of metadata related activities, and was built in a future proof way that we ended up not needing so far. I would recommend you just leave it out
