### ISSUE TITLE
Report new samples loaded on sv_pipeline/load_data.py

### ISSUE THREAD

**Issue by williamphu** [macarthur-lab/hail-elasticsearch-pipelines#212]
Have the pipeline report any samples that have been newly loaded or updated for a project.

**Comment by hanars** [comment]
The pipeline doesn't really have any way of accessing previous runs - it doesn't have any way to know what the old index was, or what the old subset file was. This probably will work better as a seqr feature request - maybe when you add a new index via the UI it tells you which samples were new after it succeeds

**Comment by williamphu** [comment]
Makes sense to me. Closing this issue here.
