### ISSUE TITLE
VEP annotation discrepancy

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/hail-elasticsearch-pipelines#35]
Eg. No variants seen for ACTN3 in the new browser b/c they are not annotated as being in the gene.

http://gnomad.broadinstitute.org/gene/ENSG00000248746

http://gnomad-beta.broadinstitute.org/gene/ACTN3

**Comment by nawatts** [comment]
This is due to a problem in the Elasticsearch query in gnomadjs, not the annotation pipeline.
