### ISSUE TITLE
Update CADD scores

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/hail-elasticsearch-pipelines#43]
We're currently using precomputed SNP and INDEL CADD scores v1.3 (released in 2015).
CADD v1.4 just got released 1 month ago, and has 
```
... support of the genome build GRCh38/hg38, and also includes a new CADD model for GRCh37/hg19. We further fixed some minor issues identified in CADD v1.3 with respect to how annotations were interpreted in the model and updated some of the underlying datasets. We included a new splice score (dbscSNV) and measures of genome-wide variant density. The GRCh38 and GRCh37 models are based on the same (or, if these were not available, very similar) annotations. Comprehensive information about the new models can be found in the release notes.
```
(from http://cadd.gs.washington.edu/news, http://cadd.gs.washington.edu/download)

We should update the CADD files we currently use for annotations:
```
gs://seqr-reference-data/GRCh37/CADD/CADD_snvs_and_indels.vds
gs://seqr-reference-data/GRCh38/CADD/CADD_snvs_and_indels.vds
```
which were generated by downloading the pre-computed .tsvs from http://cadd.gs.washington.edu/download, converting them to VCFs by running

```
cat header.vcf <(zcat ../GRCh37/${input_tsv} | grep -v ^# | awk -v OFS='\t' '($3 ~ /(A|C|G|T)/) && ($4 ~ /(A|C|G|T)/) { print $1, $2, ".", $3, $4, ".", ".", "RawScore="$5";PHRED="$6 }' ) | bgzip >  ${input_base}.vcf.gz
```

in `/humgen/atgu1/fs03/shared_resources/CADD/GRCh38/`

and then converting the VCFs to VDS using https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/download_and_create_reference_datasets/hail_scripts/v01/write_cadd_vds.py

**Comment by nawatts** [comment]
`write_cadd_vds.py` is done. New VDS files are located at:

* gs://seqr-reference-data/GRCh37/CADD/CADD_snvs_and_indels.v1.4.vds
* gs://seqr-reference-data/GRCh38/CADD/CADD_snvs_and_indels.v1.4.vds
