### ISSUE TITLE
Seqr loading command does not recognized --subset-samples argument

### ISSUE THREAD

**Issue by mike-w-wilson** [macarthur-lab/hail-elasticsearch-pipelines#50]
The seqr loading command is not recognizing the --subset-sample argument 

```
bash-3.2$ python gcloud_dataproc/load_GRCh38_dataset.py --host 10.56.10.4 --subset-samples gs://seqr-datasets/GRCh38/Rare_Genomes_Project/RGP_ids.txt --project-guid Rare_Genomes_Project --sample-type WGS --dataset-type GATK_VARIANTS --remap-sample-ids gs://seqr-datasets/GRCh38/Rare_Genomes_Project/remap_ids.txt gs://seqr-datasets/GRCh38/RDG_WGS_Broad_Internal/v1/RDG_WGS_Broad_Internal.vcf.gz
(re)download fam file from seqr? [Y/n]
```
According to the repo, this should only come up when a fam file or a subset file is not supplied. 

Thanks!

**Comment by nawatts** [comment]
Looks like it prompts unless *both* `--fam-file` and `--subset-samples` are specified.

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/gcloud_dataproc/utils/seqr_api.py#L34-L43

**Comment by mike-w-wilson** [comment]
Thanks Nick! I totally misread that. My new question is if the prompt is necessary for small loadings, sub 250 samples.  Previously it was required over 250 samples to maintain relationships in the ES indices. Basically if it is required for all loadings now, would it be possible to remove the test/prompt and just pull the ped?

**Comment by bw2** [comment]
Hana's latest PR adds a --download-fam-file flag.  Without it, prompts are skipped.
